### ISSUE TITLE
[Bug]: Docs are not available?

### ISSUE THREAD

**Issue by ikari7789** [Laravel-Lang/common#155]
### Lang Package Name

laravel-lang/lang

### Lang Package Version

N/A

### Laravel Framework Version

N/A

### PHP Version

N/A

### Issue description

Not sure if this is the correct repository to post this in, but seems https://laravel-lang.com is not pointing to any active GH pages currently and only resolves to 404.

### Steps to reproduce

Access https://laravel-lang.com via the browser.

**Comment by andrey-helldar** [comment]
GitHub today began requiring verification of domain name ownership. Thanks for noticing. I'm fixing the problem.

**Comment by ikari7789** [comment]
Thank you for the quick reply! I couldn't figure out which repository was supposed to be hosting it! Hope you can get the issue resolved without much headache.

**Comment by andrey-helldar** [comment]
We direct research from all repositories to this one. Therefore it is positioned correctly.

I made a temporary redirect to a backup site until we solved the problem with the domain name.

Thank you for your message!

**Comment by andrey-helldar** [comment]
The problem with the domain name has been resolved. Thank you for your message!
