### ISSUE TITLE
Missing country code SX Sint Maarten (Dutch Part)

### ISSUE THREAD

**Issue by dmason30** [Laravel-Lang/common#167]
https://github.com/Laravel-Lang/native-country-names

### Feature description

https://www.iso.org/obp/ui/#iso:code:3166:SX

**Comment by dmason30** [comment]
> Sorry, but `SX` locale is not supported by [CLDR](https://cldr.unicode.org/).
> 
> ```
> Source location : https://punic.github.io/data
> CLDR version    : latest available
> Format versions : 1 2
> Locales         : sx
> Output directory: vendor/punic/punic/src/data
> Fetching data state... done.
> Determining the latest CLDR version... 42
> 
> The locale sx is not supported.
> ```
> 
> Use the [Dutch localization code](https://laravel-lang.com/available-locales-list.html#lists-available-locales-nl) instead.

But this is not about adding it as a locale? This is adding as a ISO country code to the country names package?

**Comment by andrey-helldar** [comment]
The fact is that the "Native Country Names" package uses the [ISO-639-1](https://localizely.com/iso-639-1-list/) list as a source, including from which [CLDR](https://cldr.unicode.org/) receives information. We do not manually enter country names, they are loaded automatically. This service does not know about the existence of the `sx` localization code.

**Comment by dmason30** [comment]
> The fact is that the "Native Country Names" package uses the [ISO-639-1](https://localizely.com/iso-639-1-list/) list as a source, including from which [CLDR](https://cldr.unicode.org/) receives information. We do not manually enter country names, they are loaded automatically. This service does not know about the existence of the `sx` localization code.

Thanks for taking the time to explain Andrey, understood.

**Comment by andrey-helldar** [comment]
No problem, Daniel.
As soon as CLDR learns to understand this localization code, we will definitely add it. Thank you for your message!
