### ISSUE TITLE
[Bug]: Aliases are ignored in certain commands

### ISSUE THREAD

**Issue by chillbram** [Laravel-Lang/common#170]
### Lang Package Name

laravel-lang/publisher

### Lang Package Version

16.2.0

### Laravel Framework Version

10.43.0

### PHP Version

8.2

### Issue description

I use aliases for the languages to make them compatible with [RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646). In my use case I have Dutch aliased to `nl-NL`. It seems to recognize this correctly, but it's not handled correctly in various commands:

- `php artisan lang:add nl` -> works as intended
- `php artisan lang:add nl-NL` -> it recognizes the language, but translation files are in English
- `php artisan lang:update` -> it recognizes the correct languages, but all aliased languages are translated to English

I've tested this with multiple aliases for different languages and this behaviour is consistent.

### Steps to reproduce

1. Alias in `localization.php` is set with `[Locale::Dutch->value => 'nl-NL']`
2. Run either `php artisan lang:update` or `php artisan lang:add nl-NL`
3. Translation files are created or updated in the correct location, but are filled with the English translations

**Comment by andrey-helldar** [comment]
I saw this problem. The `lang:add nl-NL` command creates the correct files, but the other one, `lang:update`, publishes the English language.

**Comment by andrey-helldar** [comment]
Fixed in version [16.2.1](https://github.com/Laravel-Lang/publisher/releases/tag/16.2.1).

Thank you for the report!

**Comment by chillbram** [comment]
Great! Thanks as always for the quick responses :)
