### ISSUE TITLE
[Bug]: Some lines are not translated, although there is a translation in the package.

### ISSUE THREAD

**Issue by lopatin96** [Laravel-Lang/common#181]
### Lang Package Name

laravel-lang/lang

### Lang Package Version

15.1.5

### Laravel Framework Version

10.30.0

### PHP Version

8.2.12

### Dependencies

```
"require-dev": {
        "laravel-lang/common": "^6.1",
        "laravel-lang/actions": "^1.7",
        "laravel-lang/attributes": "^2.10",
        "laravel-lang/lang": "*",
},
```

My **es.json** file does not contain the Spanish translation for a string
"Ensure your account is using a long, random password to stay secure.":

![Screenshot 2024-04-28 at 00 06 57](https://github.com/Laravel-Lang/common/assets/18104593/8277c3d1-f9ab-458b-98bd-b7d8cc7921ef)

But I discovered that there actually is a translation in **vendor\laravel-lang\lang\locales\es\json.json**:

![Screenshot 2024-04-28 at 00 08 46](https://github.com/Laravel-Lang/common/assets/18104593/d3c47ce8-5ccc-4391-bac0-fb59415b3cfa)

Help me figure out what I'm doing wrong or is this possibly a bug?

### Issue description

I added Spanish lang with
`php artisan lang:add es`

Then updated local files
`php artisan lang:update`

and I noticed that not all lines in es.json contain a Spanish translation (instead of the Spanish one, the default version is English). I thought that translation simply did not exist but then I discovered that in fact there was a translation, it was just not being added to my file for some reason... 

### Steps to reproduce

composer require --dev laravel-lang/common
php artisan lang:add es

**Comment by andrey-helldar** [comment]
Fix for Laravel 10:

```bash
composer require --dev laravel-lang/lang:^14.0
```
The problem is that support for Laravel 10 has been removed from the 15th version of the package due to a conflict of validation keys with Laravel 11, but since we still support this version, we cannot severely restrict it in the Common package.

You can see that in a [compatibility table](https://laravel-lang.com/release-notes.html#lang).

**Comment by lopatin96** [comment]
@andrey-helldar thank you very much!
