### ISSUE TITLE
New translation

### ISSUE THREAD

**Issue by sloukapetr** [Laravel-Lang/common#184]
### Feature description

Please add validation.captha.

EN:
'captcha'              => 'The :attribute field is wrong.',

CS:
'captcha'              => 'Pole :attribute není správné.',

**Comment by andrey-helldar** [comment]
Are these phrases translated in some Laravel project or is it your desire to add new keys?

If from a project, please provide a link to it.

If it is your wish, you can easily create your own connection package using our [template](https://github.com/Laravel-Lang/translations-template).

**Comment by sloukapetr** [comment]
Its from https://github.com/mewebstudio/captcha

**Comment by andrey-helldar** [comment]
Got it. In this case you can create your own project with translations following the instructions: 

https://github.com/Laravel-Lang/translations-template?tab=readme-ov-file#steps
