### ISSUE TITLE
[Bug]: laravel-lang/lang 15 doesn't support Laravel 10.x, so version 6.2 breaks compatibility with Laravel 10.x

### ISSUE THREAD

**Issue by neurotools** [Laravel-Lang/common#185]
### Lang Package Name

laravel-lang/common

### Lang Package Version

6.2

### Laravel Framework Version

10.48.10

### PHP Version

8.3.7

### Dependencies

```json
"require": {
        "php": "^8.1",
        "anhskohbo/no-captcha": "^3.6",
        "aws/aws-sdk-php-laravel": "^3.9.0",
        "dyrynda/laravel-cascade-soft-deletes": "^4.4.0",
        "guzzlehttp/guzzle": "^7.8.1",
        "laravel/framework": "^10.48.10",
        "laravel/sanctum": "^3.3.3",
        "laravel/tinker": "^2.9",
        "maatwebsite/excel": "^3.1.55",
        "tcg/voyager": "^1.6.x-dev",
        "transbank/transbank-sdk": "^4.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": ">=3",
        "fakerphp/faker": "^1.23.1",
        "freshwork/chilean-bundle": "^2.1.4",
        "laravel-lang/common": "^6.1.0",
        "laravel/pint": "^1.15.3",
        "laravel/sail": "^1.29.1",
        "mockery/mockery": "^1.6.11",
        "nunomaduro/collision": "^7.10",
        "phpunit/phpunit": "^10.5.20",
        "spatie/laravel-ignition": "^2.7",
        "twbs/bootstrap": "^5.3.3"
    },
```

### Issue description

The package laravel-lang/lang version 15 dropped support for Laravel 10.x

Pull request  #175 added laravel-lang/lang version 15 support to laravel-lang/common package, tha was merged on 6.2, breaking translations on Laravel 10.x.

### Steps to reproduce

1. Create a new Laravel 10.x app
2. Add laravel-lang/common 6.2
3. Call artisan lang:add es

Only 3 php files are copied to /lang/es

- lang/es/actions.php
- lang/es/http-statuses.php
- lang/es/validation.php

And 1 JSON file to /lang
- lang/es/es.json

Expected to see: 
- lang/es/actions.php
- lang/es/auth.php
- lang/es/http-statuses.php
- lang/es/pagination.php
- lang/es/passwords.php
- lang/es/validation.php

And for example, validation.php is missing many keys, like 'required'.

**Comment by andrey-helldar** [comment]
It's not a bug. It's a version difference. Yes, [Common 6](https://laravel-lang.com/release-notes.html#common) supports Laravel 10 and 11, but the [Lang](https://laravel-lang.com/release-notes.html#lang) package it installs is version-separated:

- 14.0 - Laravel 10, 11*
- 15.0 - Laravel 11

So, to correctly install dependencies for a previous version of Laravel, you need to run an additional console command:

```bash
composer require --dev laravel-lang/lang:^14.0
```

Related issue: https://github.com/Laravel-Lang/common/issues/181

**Comment by andrey-helldar** [comment]
We have added [this](https://laravel-lang.com/installation.html) information to the documentation.

![image](https://github.com/Laravel-Lang/common/assets/10347617/8e571894-8ed3-494c-8901-871333e25254)
