### ISSUE TITLE
[Bug]: LaravelLang\Config\Data\Hidden\ModelsData::__construct(): Argument #1 ($directory) must be of type string, null given, called in ****/vendor/laravel-lang/config/src/Services/Config.php on line 51

### ISSUE THREAD

**Issue by echo-LuGuang** [Laravel-Lang/common#192]
### Lang Package Name

laravel-lang/common

### Lang Package Version

6.3.0

### Laravel Framework Version

v11.9.2

### PHP Version

PHP 8.2.17 (cli) (built: Mar 12 2024 14:26:30) (NTS)

### Dependencies

Problems that arise after composer update

### Issue description

Problems that arise after composer update

### Steps to reproduce

Problems that arise after composer update

**Comment by enrymari** [comment]
Maybe the problem comes from updating laravel-lang/config to 1.4.0?
Downgrading laravel-lang/config to 1.3.0 there are no issue.

**Comment by echo-LuGuang** [comment]
Problem repeated, close

https://github.com/Laravel-Lang/common/issues/191

**Comment by andrey-helldar** [comment]
The bug has been fixed in version [1.4.1](https://github.com/Laravel-Lang/config/releases/tag/1.4.1) of `laravel-lang/config` package.

Once again I apologize for the inconvenience. This was a bug that could not be detected during preliminary testing.

Thank you for your report!
