### ISSUE TITLE
[Bug]: TypeError

### ISSUE THREAD

**Issue by maxleistner** [Laravel-Lang/common#195]
### Lang Package Name

laravel-lang/locales

### Lang Package Version

2.9.1

### Laravel Framework Version

11.11.1

### PHP Version

8.2

### Issue description

```
sail artisan lang:update

   TypeError

  LaravelLang\Locales\Services\RawLocales::LaravelLang\Locales\Services\{closure}(): Argument #1 ($locale) must be of type string, null given

  at vendor/laravel-lang/locales/src/Services/RawLocales.php:62
     58▕                     $this->protects(),
     59▕                 )
     60▕                 ->flatten()
     61▕                 ->map(fn (string $name) => $this->toAlias(Path::filename($name)))
  ➜  62▕                 ->filter(fn (string $locale) => $this->isAvailable($locale))
     63▕                 ->when(! $withProtects, fn (Collection $items) => $items->filter(
     64▕                     fn (string $locale) => ! $this->isProtected($locale)
     65▕                 ))
     66▕                 ->unique()

      +19 vendor frames

  20  artisan:13
      Illuminate\Foundation\Application::handleCommand()
 ```

### Steps to reproduce

run `sail composer update`
run `sail artisan lang:update`

**Comment by andrey-helldar** [comment]
I saw a place to put in a hotfix, but I assume it could cause other problems.

In this situation it's best to find the cause and start fixing it from there.

Let's do this:

1. Please send me the structure of the contents of the "lang" folder. For example:
    ```
    lang/en/
    lang/en.json
    lang/vendor/en.json
    lang/vendor/some/en/
    ...
    ```
3. Try to install the previous version of localization and after that update the files. Will the problem occur?
    ```bash
    sail composer require laravel-lang/locales:2.9.0
    sail artisan lang:update
    ```

**Comment by andrey-helldar** [comment]
@maxleistner I saw in your screenshot what exactly needs to be done and will add tests to cover this case soon to avoid this problem in the future during the testing phase.

Thank you for your feedback!
