### ISSUE TITLE
[Bug]: Undefined property: LaravelLang\Config\Data\Shared\ModelsData::$connection

### ISSUE THREAD

**Issue by lovemintblue** [Laravel-Lang/common#204]
### Lang Package Name

laravel-lang/lang

### Lang Package Version

6.4

### Laravel Framework Version

11.27.2

### PHP Version

8.3

### Issue description

php artisan migrate.     [Bug]: Undefined property: LaravelLang\Config\Data\Shared\ModelsData::$connection

### Steps to reproduce

php artisan migrate

**Comment by lovemintblue** [comment]
> Look at #202 issue. I have a feeling this will help you.

Very helpful. thank you.

**Comment by andrey-helldar** [comment]
👍
