### ISSUE TITLE
[Bug]: Missing Country: Canada

### ISSUE THREAD

**Issue by timjeep** [Laravel-Lang/common#205]
### Lang Package Name

laravel-lang/native-country-names

### Lang Package Version

1.4.0

### Laravel Framework Version

11

### PHP Version

8.2.13

### Issue description

When I run:
`CountryNames::get('en', SortBy::Value)`
the country 'Canada' is not in the list.

### Steps to reproduce

`CountryNames::get('en', SortBy::Value)`

**Comment by timjeep** [comment]
I get that your answers explains why Canada isn't on the list.  However, the problem still remains that your function to get a list of country names is not complete.  Perhaps I didn't read the documentation.
I will find another package to meet my needs.
thanks...Tim

**Comment by andrey-helldar** [comment]
@timjeep You can use Punic:

```bash
# install dependency
composer require punic/punic

# load data
vendor/bin/punic-data -l +en_CA
```

Using:
```php
use Punic\Data;
use Punic\Territory;

$localeCodes = ['en', 'en_CA', 'en_BR', 'fr', 'de_DE'];
$locale      = 'fr';

$items = [];

foreach ($localeCodes as $localeCode) {
    $code = Data::getTerritory($localeCode);

    $items[$code] = [
        'code' => $code,
        'name' => Territory::getName($code, $locale),
    ];
}

return $items;
```
Result:
```bash
array:5 [
  "US" => array:2 [
    "code" => "US"
    "name" => "États-Unis"
  ]
  "CA" => array:2 [
    "code" => "CA"
    "name" => "Canada"
  ]
  "BR" => array:2 [
    "code" => "BR"
    "name" => "Brésil"
  ]
  "FR" => array:2 [
    "code" => "FR"
    "name" => "France"
  ]
  "DE" => array:2 [
    "code" => "DE"
    "name" => "Allemagne"
  ]
]
```
