### ISSUE TITLE
[Bug]: auth.password is translated to "The password is incorrect." in the php files.

### ISSUE THREAD

**Issue by MGeurts** [Laravel-Lang/common#206]
### Lang Package Name

laravel-lang/lang

### Lang Package Version

15.9.0

### Laravel Framework Version

11

### PHP Version

8.3

### Dependencies

    "require": {
        "php": "^8.3",
        "filament/tables": "^3.2",
        "intervention/image": "^3.8",
        "khill/lavacharts": "^3.1",
        "korridor/laravel-has-many-merged": "^1.1",
        "laravel/framework": "^11.28",
        "laravel/jetstream": "^5.3",
        "laravel/sanctum": "^4.0",
        "laravel/tinker": "^2.10",
        "larswiegers/laravel-translations-checker": "^0.9.2",
        "liberu-genealogy/php-gedcom": "^2.0",
        "livewire/livewire": "^3.5",
        "opcodesio/log-viewer": "^3.11",
        "spatie/laravel-activitylog": "^4.8",
        "spatie/laravel-backup": "^9.1",
        "spatie/laravel-login-link": "^1.3",
        "spatie/laravel-medialibrary": "^11.9",
        "stefangabos/world_countries": "^2.9",
        "stevebauman/location": "^7.3",
        "tallstackui/tallstackui": "^1.35"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.14",
        "barryvdh/laravel-ide-helper": "^3.1",
        "fakerphp/faker": "^1.23",
        "laravel-lang/lang": "^15.9",
        "laravel/pint": "^1.18",
        "laravel/sail": "^1.36",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.5",
        "phpunit/phpunit": "^11.4",
        "spatie/laravel-ignition": "^2.8"
    },

### Issue description

The value auth.password is translated incorrectly to "**The password is incorrect**.".
It should translate to "**Password**".
It should be corrected in all languages.

### Steps to reproduce

Install the package and look at auth.

**Comment by andrey-helldar** [comment]
No, it doesn't. This translation belongs to the validator action, not the field name.

Previously, the original translation was “The password is incorrect”. Later it was [changed](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Translation/lang/en/auth.php#L17) to “The provided password is incorrect.”.
