### ISSUE TITLE
Weird repository

### ISSUE THREAD

**Issue by andrey-helldar** [Laravel-Lang/common#78]
### Feature description

@caouecs, hi!

We have a strange repository in our organization. Can you remove it?

https://github.com/Laravel-Lang/ja-docs-10.x

![image](https://user-images.githubusercontent.com/10347617/226146257-f5e2885a-8562-49dd-a7ca-20feee473821.png)

**Comment by caouecs** [comment]
done

**Comment by andrey-helldar** [comment]
Thank you.

I have three options for how this could happen:

1. Someone from the team members creating the fork accidentally chose the namespace of the organization.
2. Someone's token was compromised (but then there would already be a lot of projects here, and this one refers to Lara)
3. A security hole has been found in Github. But, again, the project is specific. It just looks a lot like someone's personal fork despite the fact that logically it fits into the concept of our project, but if it wasn't fork.
