### ISSUE TITLE
Laravel Spark Stripe 

### ISSUE THREAD

**Issue by jackdaniel8** [Laravel-Lang/common#82]
### Environment

Laravel 9
Laravel Lang 12.0
Laravel Spark 4.x

### Issue description

Hi, 

English : 375 lines
French : 336 lines

Missing 39 translations.

Thank you

### Steps to reproduce

Install Laravel 9
Install Laravel Spark / Stripe

**Comment by andrey-helldar** [comment]
I will request up-to-date translation keys from the Laravel Core team and come back with an answer later.

**Comment by andrey-helldar** [comment]
We've received a fresh list of keys (https://github.com/Laravel-Lang/lang/pull/3079).

In the near future we will translate them or Google Translate will do it for us if it arrives earlier (at 00:00 UTC) 🙂

Thank you for issue!
