### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by ivose** [Laravel-Lang/common#83]
### Environment

- Laravel-Lang Common Version:
- Laravel Version: 10
- PHP Version: 8.2.4

### Issue description

 - Downloading laravel-lang/common (v3.1.1)
  0/12 [>---------------------------]   0%    Failed to download caouecs/laravel-lang from dist: The "https://api.github.com/repos/caouecs/lang/zipball/2cb9932f781415f1669ce27d29e5b86399ab164a" file could not be downloaded (HTTP/2 404 ):                                                                                             
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#download-a-repository-archive"}                                                                                                    
    Now trying to download from source
  - Syncing caouecs/laravel-lang (7.0.3) into cache
Cloning failed using an ssh key for authentication, enter your GitHub credentials to access private repos
When working with _public_ GitHub repositories only, head to https://github.com/settings/tokens/new?scopes=&description=Composer+on+LAPTOP-0KNMEE5S+2023-04-07+1029 to retrieve a token.
This token will have read-only permission for public information only.
When you need to access _private_ GitHub repositories as well, go to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+LAPTOP-0KNMEE5S+2023-04-07+1029
Note that such tokens have broad read/write permissions on your behalf, even if not needed by Composer.       
Tokens will be stored in plain text in "C:/Users/ivo/AppData/Roaming/Composer/auth.json" for future use by Composer.
For additional information, check https://getcomposer.org/doc/articles/authentication-for-private-packages.md#github-oauth

### Steps to reproduce

I tried "composer require --dev laravel-lang/common".

**Comment by andrey-helldar** [comment]
It looks like your application contains the `caouecs/laravel-lang` package, which was the name before it was renamed to `laravel-lang/lang`.

Therefore, you need to follow two simple steps:

1. `composer remove caouecs/laravel-lang`
2. `composer require --dev laravel-lang/common`

**Comment by andrey-helldar** [comment]
@ivose, did you manage to solve the problem?

**Comment by andrey-helldar** [comment]
Perhaps your problem is also related to https://github.com/Laravel-Lang/common/issues/86

Try installing dependencies
