### ISSUE TITLE
PHP 7.3 and Laravel 8 installation problem

### ISSUE THREAD

**Issue by Sogl** [Laravel-Lang/common#88]
### Environment

- Laravel-Lang Common Version: 1.x
- Laravel Version: 8.83.27
- PHP Version: PHP 7.3.33

### Issue description

I used 2 packets before:
```
"laravel-lang/lang": "^10.1",
"andrey-helldar/laravel-lang-publisher": "^10.0",
```

I want to update all to the current version. 

1. I removed both packages according to [upgrade guide](https://laravel-lang.com/installation/upgrade-guide/):
```
composer remove andrey-helldar/laravel-lang-publisher laravel-lang/lang
```

2. And then added `common` package for PHP 7.3 ([compatibility table](https://laravel-lang.com/installation/compatibility/common.html)):
```
composer require laravel-lang/common:^1.0
```

Conflicts:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel-lang/common ^1.0 -> satisfiable by laravel-lang/common[v1.0.0, 1.x-dev].
    - laravel-lang/common[v1.0.0, ..., 1.x-dev] require laravel-lang/publisher ^12.0 -> satisfiable by laravel-lang/publisher[v12.0.0, ..., 12.x-dev].
    - laravel-lang/publisher[v12.1.0, ..., 12.x-dev] require dragon-code/support ^5.6 -> satisfiable by dragon-code/support[v5.6.1, ..., 5.x-dev].
    - laravel-lang/publisher v12.0.0 requires dragon-code/support ^5.4 -> satisfiable by dragon-code/support[v5.4.0, ..., 5.x-dev].
    - dragon-code/support[v5.1.0, ..., 5.x-dev] conflict with andrey-helldar/support *.
    - dragon-code/pretty-routes v2.3.2 requires andrey-helldar/support ^2.0|^3.0|^4.0 -> satisfiable by andrey-helldar/support[v3.25.1].
    - dragon-code/pretty-routes is locked to version v2.3.2 and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### Steps to reproduce

1. Install Laravel 8 on PHP 7.3
2. Install `"dragon-code/pretty-routes": "^2.3"` packet (`composer require dragon-code/pretty-routes --dev` [from its repo](https://github.com/TheDragonCode/pretty-routes#laravel-framework))
3. Install `laravel-lang/common:^1.0`

**Comment by Sogl** [comment]
I don't know why `pretty-routes` 2.3.2 is installed when version 3.3.0 is available. Forcing the latest version solved the problem.

But another one came up (the process took quite a long time):
```
laradock@3edd7fd0dc0c:/var/www/sogl$ php artisan lang:add ru
Processing LaravelLang\Attributes\Provider...
Processing LaravelLang\HttpStatuses\Provider...
Processing LaravelLang\Lang\Provider...
Saving changes...

   ParseError 

  syntax error, unexpected 'static' (T_STATIC)

  at vendor/dragon-code/contracts/src/Pretty/Arr/Caseable.php:17
     13▕     public const PASCAL_CASE = 4;
     14▕ 
     15▕     public const SNAKE_CASE = 2;
     16▕ 
  ➜  17▕     public function setCase(int $type = self::NO_CASE): static;
     18▕ }
     19▕ 

      +1 vendor frames 
  2   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("DragonCode\Contracts\Pretty\Arr\Caseable")

      +3 vendor frames 
  6   [internal]:0
      Composer\Autoload\ClassLoader::loadClass("DragonCode\PrettyArray\Services\Formatter")
```

**Comment by andrey-helldar** [comment]
The problem is that package "dragon-code/pretty-routes" version 2.3 requires dependency "andrey-helldar/support" while "laravel-lang/common" version 1.0 requires "laravel-lang/publisher" version 12 , and it requires "dragon-code/support".

A long time ago the "andrey-helldar/support" package was renamed to "dragon-code/support".

That is why you saw a conflict during installation.

Next, regarding the "syntax error, unexpected 'static' (T_STATIC)" error. In the latest version of the "dragon-code/contracts" package, the method typing associated with the "dragon-code/pretty-array" project has been corrected. Since we do not support older versions of packages, we recommend that you explicitly install the dependency using the console command:

```bash
composer require dragon-code/contracts:2.19.1
```

**Comment by andrey-helldar** [comment]
In your case, I recommend using the following command to install dependencies:

```bash
composer remove laravel-lang/common laravel-lang/lang laravel-lang/publisher andrey-helldar/laravel-lang-publisher dragon-code/pretty-array andrey-helldar/pretty-array dragon-code/pretty-routes andrey-helldar/pretty-routes

composer require --dev laravel-lang/common:^1.0 dragon-code/contracts:2.19.1 dragon-code/pretty-routes
```

**Comment by Sogl** [comment]
Adding `composer require dragon-code/contracts:2.19.1` solved my problem. Thx!

**Comment by andrey-helldar** [comment]
Your welcome!
